services:
  db:
    image: postgres:18
    restart: unless-stopped
    container_name: otus-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: otus-db
    ports:
      - "5435:5432"
    volumes:
      - db:/var/lib/postgresql

volumes:
  db:
