global:
  scrape_interval: 5s

scrape_configs:
  - job_name: patroni
    metrics_path: /metrics
    static_configs:
      - targets:
          - 192.168.139.129:8008
          - 192.168.139.142:8008
          - 192.168.139.90:8008

  - job_name: postgres
    static_configs:
      - targets:
          - 192.168.139.129:9187
          - 192.168.139.142:9187
          - 192.168.139.90:9187

  - job_name: haproxy
    static_configs:
      - targets:
          - 192.168.139.90:9101
